name: SonarQube Scan

on: [push, pull_request]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run SonarQube Scanner in Docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Agrega tu token de SonarQube aquí
      run: |
        docker run --rm \
          -e SONAR_HOST_URL=http://localhost:9000 \
          -e SONAR_LOGIN=$SONAR_TOKEN \
          -v $(pwd):/usr/src \
          sonarsource/sonar-scanner-cli \
          sonar-scanner \
          -Dsonar.projectKey=mi_repositorio_readme \  # Reemplaza con tu Project Key
          -Dsonar.sources=. \
          -X  # Habilitar el modo de depuración
